export const configs = {

    currencies: {
        'acmft': 'Fan Token ASR',
        'acordo01': 'None',
        'asrft': 'Fan Token ASR',
        'atmft': 'Fan Token ATM',
        'bch': 'Bitcoin Cash',
        'btc': 'Bitcoin',
        'caift': 'Fan Token CAI',
        'chz': 'Chiliz',
        'eth': 'Ethereum',
        'galft': 'Fan Token GAL',
        'imob01': 'None',
        'juvft': 'Fan Token JUV',
        'link': 'CHAINLINK',
        'ltc': 'Litecoin',
        'mbcons01': 'Cota de Consórcio 01',
        'mbcons02': 'Cota de Consórcio 02',
        'mbfp01': 'None',
        'mbfp02': 'None',
        'mbprk01': 'Precatório MB SP01',
        'mbprk02': 'Precatório MB SP02',
        'mbprk03': 'Precatório MB BR03',
        'mbprk04': 'Precatório MB RJ04',
        'mbvasco01': 'MBVASCO01',
        'mco2': 'MCO2',
        'ogft': 'Fan Token ASR',
        'paxg': 'PAX Gold',
        'psgft': 'Fan Token PSG',
        'usdc': 'USD Coin',
        'wbx': 'WiBX',
        'xrp': 'XRP',
    }

}
